// vue-03/src/App.vue
<template>
 <div>
     <add-todo></add-todo>
     <todo-list :todos="todos"></todo-list>
     <todo-footer></todo-footer>
 </div>
</template>
<script>
import AddTodo from './AddTodo.vue'
import TodoList from './TodoList.vue'
import TodoFooter from './TodoFooter.vue'
export default {
 components: {
     AddTodo,
     TodoList,
     TodoFooter,
 },
 data () {
  return  {
      todos: [
          {
              text: '01',
              completed: false,
          },
          {
              text: '02',
              completed: true,
          }
      ]
  };
 },
 methods: {
 }
}
</script>
<style>
</style>

// react-router-00/src/app.js
import React, { Component } from 'react';
import TodoList from './TodoList'
import AddTodo from './AddTodo'

const data = [
    {
        text: '001',
        completed: false,
    },
    {
        text: '002',
        completed: false,
    },
]

class App extends Component {
    render() {
        return (
            <div>
                <AddTodo />
                <TodoList todos={data} />
            </div>
        )
    }
}

export default App
