// react-router-01/src/app.js
import React, { Component } from 'react';

import AddTodo from './AddTodo'
import TodoList from './TodoList'
import Footer from './Footer'

const data = [
    {
        text: '001',
        completed: false,
    },
    {
        text: '002',
        completed: true,
    },
]

class App extends Component {

    constructor (props) {
        super(props)
        this.onTodoClick = this.onTodoClick.bind(this)
    }

    onTodoClick (index) {
        console.log('@@@@todo click', index)
    }

    render() {
        return (
            <div>
                <AddTodo />
                <TodoList todos={data} onTodoClick={this.onTodoClick}/>
                <Footer />
            </div>
        )
    }
}

export default App

// vue-03/src/App.vue
<template>
 <div>
     <add-todo></add-todo>
     <todo-list :todos="todos"></todo-list>
     <todo-footer></todo-footer>
 </div>
</template>
<script>
import AddTodo from './AddTodo.vue'
import TodoList from './TodoList.vue'
import TodoFooter from './TodoFooter.vue'
export default {
 components: {
     AddTodo,
     TodoList,
     TodoFooter,
 },
 data () {
  return  {
      todos: [
          {
              text: '01',
              completed: false,
          },
          {
              text: '02',
              completed: true,
          }
      ]
  };
 },
 methods: {
 }
}
</script>
<style>
</style>
